server:
  servlet:
    context-path: /
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: PManager
#H2
#  datasource:
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
  datasource:
    url: jdbc:mysql://localhost:3306/pmanagerdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlroot
#  h2:
#    console:
#      enabled: true
  jpa:
    show-sql: true
    #para MySQL
    hibernate:
      ddl-auto: update
app:
  general:
    pageSize: 3
  security:
    apiKey: thekey
